### ISSUE TITLE
can update the search bar to show suggestions

### ISSUE THREAD

**Issue by anmol-284** [manzil-infinity180/Xf-Registration_frontend#11]
i can update the search bar so that it show the suggestion below as soon as i start tying

**Comment by manzil-infinity180** [comment]
Thanks @anmol-284 , lets do it and when you raise pr, please add video of it

**Comment by anmol-284** [comment]
yeah sure

**Comment by anmol-284** [comment]
please assign hacktoberfest level 2

**Comment by anmol-284** [comment]
where can i run the backend server ? sorry but unable to start it @manzil-infinity180

**Comment by manzil-infinity180** [comment]
https://github.com/manzil-infinity180/Xf-Registration this backend but you need to configure with your own credentials

**Comment by manzil-infinity180** [comment]
Feel free to ask me if you get some problem in setup I can help you with that

**Comment by anmol-284** [comment]
thank you

**Comment by anmol-284** [comment]
Sorry but i am unable to start the backend server, not having some of the google credentials

**Comment by manzil-infinity180** [comment]
closing this issue , it need some extra creditals to setup the backend which i will not expose , try to. solve some other issue
thank @anmol-284

**Comment by anmol-284** [comment]
Ok

**Comment by anmol-284** [comment]
@manzil-infinity180 Want to improve the ui of social media buttons please assign that to me
Issue #18
