### ISSUE TITLE
Improve the Social Media Buttons

### ISSUE THREAD

**Issue by anmol-284** [manzil-infinity180/Xf-Registration_frontend#18]
https://github.com/user-attachments/assets/725ac4c9-cc2e-4b2f-9981-e4f18b655f5a

I can make the social media buttons looks more unique and animated
![Screenshot 2024-10-07 213301](https://github.com/user-attachments/assets/2e924ea5-a9f4-40d8-8c53-f4c631741a51)
Just Like These

**Comment by manzil-infinity180** [comment]
did not fit with my ui
