### ISSUE TITLE
Improve Header of the page

### ISSUE THREAD

**Issue by manzil-infinity180** [manzil-infinity180/Xf-Registration_frontend#2]
<img width="1546" alt="Screenshot 2024-10-05 at 6 11 35 PM" src="https://github.com/user-attachments/assets/850fc676-f564-42b8-aca3-2e21301726ca">

On mobile page does not looks good

**Comment by uzefaqureshi06** [comment]
can you assign this to me I want to work on this issue

**Comment by uskYash** [comment]
Hi , I hope you're doing well. I I believe I can contribute effectively, and I'm eager to help resolve it. If it's possible, could you please assign me this task? I would really appreciate the opportunity. Thank you!"

**Comment by uzefaqureshi06** [comment]
can you assign this to me I want to work on this issue

**Comment by Nandinig24** [comment]
Please assign the task to me i would surely do it as a hacktoberfest contributor !

**Comment by kushal7201** [comment]
@manzil-infinity180  Kindly review my PR
